### ISSUE TITLE
Registration 500's: KeyError 'organization_name'

### ISSUE THREAD

**Issue by jacqui** [MuckRock/squarelet#37]
I just tried to register a new account for the first time and found that it's 500ing for me with the following:

```
Internal Server Error: /pp-api/register/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_auth/registration/views.py", line 46, in dispatch
    return super(RegisterView, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/generics.py", line 192, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_auth/registration/views.py", line 65, in create
    user = self.perform_create(serializer)
  File "/Users/jacqui/Projects/newscatalyst/squarelet/squarelet/users/viewsets.py", line 148, in perform_create
    user, _group_organization, _error = get_user_model().objects.register_user(data)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/Users/jacqui/Projects/newscatalyst/squarelet/squarelet/users/managers.py", line 59, in register_user
    name=user_data["organization_name"]
KeyError: 'organization_name'
```

I'm going to try figuring out the problem here and if warranted fix it, but I thought I should log it first.

**Comment by TylerFisher** [comment]
Tracked this down: the new plan model expects an organization name when users register on the free plan. We don't pass this with our frontend. 

@mitchelljkotler, if we're going to have users sign up for a free plan by default when signing up for PressPass, but they're not creating an organization at that step, how should we handle this?

**Comment by jacqui** [comment]
Thanks for finding the bigger issue @TylerFisher. 

My little workaround is this change in `squarelet/users/managers.py` (l57-60):

```
            organization_name = user_data.get("organization_name")
            if plan and plan.for_groups and organization_name:
                group_organization = Organization.objects.create(
                    name=organization_name
                )
```

Basically use `get()` and test for presence to avoid the `KeyError`
