### ISSUE TITLE
stripe.error.AuthenticationError: Invalid API Key provided: sk_muckrock

### ISSUE THREAD

**Issue by palewire** [MuckRock/squarelet#81]
I'm getting the error below when I try to request user data with an OAuth2 token. I'm making a request to `https://dev.squarelet.com/api/users/6e353d5b-cd1a-4bc5-b352-06c3549c2ced/`, which includes the access token in an Authorization Bearer header.

Here's what my code in my Flask app looks like:

```
        # Pull POST data
        type_ = request.form.get("type", "")
        uuids = request.form.getlist('uuids')
        timestamp = request.form.get("timestamp", "")
        signature = request.form.get("signature", "")

        print("type", type_)
        print("uuids", uuids)
        print("timestamp", timestamp)
        print("signature", signature)

        # Verify signature
        hmac_digest = hmac.new(
            key=app.config["OAUTH_CLIENT_SECRET"].encode("utf8"),
            msg="{}{}{}".format(timestamp, type_, "".join(uuids)).encode("utf8"),
            digestmod=hashlib.sha256,
        ).hexdigest()
        match = hmac.compare_digest(signature, hmac_digest)

        # The different type of things we can sync,
        # which is right now limited to users
        types_url = {"user": "users",}

        # Make sure th provided type is in the allowed list
        assert type_ in types_url

        # Prevent replay attacks
        assert int(timestamp) + 300 > time.time()

        # Get OAuth2 token
        auth = (
            app.config["OAUTH_CLIENT_ID"],
            app.config["OAUTH_CLIENT_SECRET"],
        )
        data = {"grant_type": "client_credentials"}
        resp = requests.post(
            app.config["OAUTH_TOKEN_URL"],
            data=data,
            auth=auth,
        )
        resp.raise_for_status()
        resp_json = resp.json()
        print("resp_json", resp_json)

        access_token = resp_json["access_token"]
        print("access_token", access_token)

        # expire a few seconds early to ensure its not expired
        # when we try to use it
        expires_in = int(resp_json["expires_in"]) - 10
        print("expires_in", expires_in)

        # Loop through all the user ids
        for uuid in uuids:
            # Get data about them from the identity provider
            headers = {
                "Authorization": f"Bearer {access_token}",
            }
            url = f"{app.config['OAUTH_URL']}api/{types_url[type_]}/{uuid}/"
            print("url", url)
            print("headers", headers)
            resp = requests.get(
                url,
                headers=headers
            )
            resp.raise_for_status()
            data = resp.json()
            print("data", data)
```

Here's the error in the Squarelet env.
```
[08/Jun/2022:20:42:17 +0000] "GET /api/users/6e353d5b-cd1a-4bc5-b352-06c3549c2ced/ HTTP/1.1" 500 59
393 "-" "python-requests/2.27.1"                                                                                                              
squarelet_django_1        | Traceback (most recent call last):                                                                                
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 76, in __call__      
squarelet_django_1        |     return self.application(environ, start_response)                                                              squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 133, in __call__               squarelet_django_1        |     response = self.get_response(request)                                                                         
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 130, in get_response           
squarelet_django_1        |     response = self._middleware_chain(request)                                                                    
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 49, in inner              
squarelet_django_1        |     response = response_for_exception(request, exc)                                                               
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception                                                                                                                                          squarelet_django_1        |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())                    
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_ex
ception                                                                                                                                       
squarelet_django_1        |     return debug.technical_500_response(request, *exc_info)              
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 40, in nu
ll_technical_500_response                                                                                                                     
squarelet_django_1        |     raise exc_value.with_traceback(tb)  
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner              
squarelet_django_1        |     response = get_response(request)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
squarelet_django_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
squarelet_django_1        |   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
squarelet_django_1        |     return func(*args, **kwds)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
squarelet_django_1        |     return view_func(*args, **kwargs)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
squarelet_django_1        |     return self.dispatch(request, *args, **kwargs)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
squarelet_django_1        |     response = self.handle_exception(exc)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
squarelet_django_1        |     self.raise_uncaught_exception(exc)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
squarelet_django_1        |     raise exc
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
squarelet_django_1        |     response = handler(request, *args, **kwargs)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 56, in retrieve
squarelet_django_1        |     return Response(serializer.data)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 555, in data
squarelet_django_1        |     ret = super().data
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 253, in data
squarelet_django_1        |     self._data = self.to_representation(self.instance)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 522, in to_representation
squarelet_django_1        |     ret[field.field_name] = field.to_representation(attribute)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 687, in to_representation
squarelet_django_1        |     self.child.to_representation(item) for item in iterable
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
squarelet_django_1        |     self.child.to_representation(item) for item in iterable
squarelet_django_1        |   File "/app/squarelet/organizations/serializers.py", line 88, in to_representation
squarelet_django_1        |     representation = super().to_representation(instance)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 522, in to_representation
squarelet_django_1        |     ret[field.field_name] = field.to_representation(attribute)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 522, in to_representation
squarelet_django_1        |     ret[field.field_name] = field.to_representation(attribute)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/fields.py", line 1886, in to_representation
squarelet_django_1        |     return method(value)
squarelet_django_1        |   File "/app/squarelet/organizations/serializers.py", line 75, in get_card
squarelet_django_1        |     return obj.customer(StripeAccounts.muckrock).card_display
squarelet_django_1        |   File "/app/squarelet/organizations/models/payment.py", line 114, in card_display
squarelet_django_1        |     if self.card:
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/memoize.py", line 11, in _property
squarelet_django_1        |     setattr(self, attribute, fn(self))
squarelet_django_1        |   File "/app/squarelet/organizations/models/payment.py", line 101, in card
squarelet_django_1        |     if self.stripe_customer.default_source: 
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/memoize.py", line 11, in _property
squarelet_django_1        |     setattr(self, attribute, fn(self))
squarelet_django_1        |   File "/app/squarelet/organizations/models/payment.py", line 92, in stripe_customer
squarelet_django_1        |     api_key=settings.STRIPE_SECRET_KEYS[self.stripe_account],
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/stripe/api_resources/abstract/createable_api_resource.py", line 17,
 in create
squarelet_django_1        |     response, api_key = requestor.request('post', url, params, headers)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/stripe/api_requestor.py", line 95, in request
squarelet_django_1        |     resp = self.interpret_response(rbody, rcode, rheaders)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/stripe/api_requestor.py", line 312, in interpret_response
squarelet_django_1        |     self.handle_error_response(rbody, rcode, resp.data, rheaders)
squarelet_django_1        |   File "/usr/local/lib/python3.6/site-packages/stripe/api_requestor.py", line 120, in handle_error_response
squarelet_django_1        |     raise err
squarelet_django_1        | stripe.error.AuthenticationError: Invalid API Key provided: sk_muckrock
```

**Comment by palewire** [comment]
This was fixed by creating a real Squarelet account and putting a real API key into the .django env configuration file.
